### ISSUE TITLE
Plugin rendering issue

### ISSUE THREAD

**Issue by Spunge** [OpenMusicKontrollers/synthpod#38] opened 2019-07-28 20:58 UTC
Zyn-fusion's interface sporadically does not show, and sometimes does show but render incorrectly. The problem is only visual, buttons are at the correct positions:

![image](https://user-images.githubusercontent.com/1842108/62012795-08ef9400-b18b-11e9-85d7-1949d1e38156.png)

When it doesn't show i'm getting the same artifacts as described in #33, though it not showing is quite rare.

This has no priority for me as closing and opening the GUI will most of the times result in a working GUI. I just thought you'd like to know.

**Comment by Spunge** [comment] 2019-07-29 10:25
Here's the xwindow output from a zyn-fusion window that does not show: [zynfusion_window.log](https://github.com/OpenMusicKontrollers/synthpod/files/3441534/zynfusion_window.log)

**Comment by ventosus** [comment] 2019-07-29 10:45
Well, I've remove the quirk that ignores windows of min/max size 1x1 as I though it was caused by the uninitialized structure fixed in #33.

Apparently, it seems that Zyn really sometimes announces its size as being 1x1, which is totally unreasonable, of course.

**Comment by ventosus** [comment] 2019-07-29 21:03
Was able to reproduce this. Quirk that does ignore invalid X11 window size hints readded in a5bc958facd9e93aec1cae6bb341cc8026b432c2

**Comment by Spunge** [comment] 2019-07-30 08:26
> Apparently, it seems that Zyn really sometimes announces its size as being 1x1, which is totally unreasonable, of course.

Weird. I'll report it to the zyn-fusion maintainer, thanks for checking.

**Closed** 2019-07-30 08:46 UTC
